name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --extras dev

      - name: Run tests
        run: poetry run pytest
